default_language_version:
  python: python3.10

default_stages: [commit]

repos:
  - repo: https://github.com/asottile/reorder_python_imports
    rev: v2.6.0
    hooks:
      - id: reorder-python-imports
        args:
          - --py38-plus

  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        args:
          - --line-length=120
          - --target-version=py310

  - repo: https://github.com/PyCQA/flake8
    rev: 4.0.1
    hooks:
      - id: flake8
        args:
          - --max-line-length=120
          - --max-cognitive-complexity=20
          - --ignore=E203,W503 # E203,W503 for black compatibility
        additional_dependencies:
          - pep8-naming==0.12.1
          - flake8-absolute-import==1.0
          - flake8-bugbear==21.11.29
          - flake8-builtins==1.5.3
          - flake8-class-attributes-order==0.1.2
          - flake8-cognitive-complexity==0.1.0
          - flake8-comprehensions==3.7.0
          - flake8-pytest-style==1.5.1

  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.0.1
    hooks:
      - id: debug-statements
      - id: requirements-txt-fixer # order requirements alphabetically
      - id: check-ast # Simply check whether the files parse as valid python
      - id: check-case-conflict # Check for files that would conflict in case-insensitive filesystems
      - id: check-builtin-literals # Require literal syntax when initializing empty or zero Python builtin types
      - id: check-docstring-first # Check a common error of defining a docstring after code
      - id: check-merge-conflict # Check for files that contain merge conflict strings
      - id: check-yaml # Check yaml files
      - id: end-of-file-fixer # Ensure that a file is either empty, or ends with one newline
      - id: mixed-line-ending # Replace or checks mixed line ending
      - id: trailing-whitespace # This hook trims trailing whitespace

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.910-1
    hooks:
    - id: mypy

  - repo: https://github.com/asottile/pyupgrade
    rev: v2.29.1
    hooks:
      - id: pyupgrade
        args:
          - --py38-plus
